//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ChunkedCodingParserData, NSFileHandle;

@interface ChunkedCodingParser : NSObject
{
    int theStep;
    unsigned int theChunkSize;
    unsigned int theLeftBodySize;
    BOOL doNeedMoreData;
    BOOL inQuoted;
    BOOL inSlashed;
    long long useOriginBody;
    ChunkedCodingParserData *theIn;
    NSFileHandle *_outFileHandle;
}

@property(retain, nonatomic) NSFileHandle *outFileHandle; // @synthesize outFileHandle=_outFileHandle;
- (void).cxx_destruct;
- (int)currentStep;
- (void)parseLastChunkExtension;
- (BOOL)findCrlf:(unsigned int *)arg1 crlfEnd:(unsigned int *)arg2 quoted:(char *)arg3 slashed:(char *)arg4;
- (BOOL)findCrlf:(unsigned int *)arg1 crlfEnd:(unsigned int *)arg2;
- (void)parseTrailer;
- (void)parseChunkEnd;
- (void)parseChunkBody;
- (void)parseUnusedChunkExtension;
- (void)parseChunkSize;
- (BOOL)needsMoreData;
- (_Bool)mayContinue;
- (BOOL)parse:(id)arg1;
- (id)init;

@end

