//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "ConnectorDispatchQueueProvider.h"
#import "SGGCDAsyncSocketDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString, OutgoingSelector, SGGCDAsyncSocket, SettingsModel;

@interface ConnectionManager : BaseObject <ConnectorDispatchQueueProvider, SGGCDAsyncSocketDelegate>
{
    NSMutableDictionary *_waitingQueueMap;
    NSObject<OS_dispatch_source> *_timeoutTimer;
    NSMutableArray *_incomingConnections;
    NSMutableArray *_tunnelConnections;
    NSMutableDictionary *_outgoingConnectionMap;
    SGGCDAsyncSocket *_listener;
    SettingsModel *_settingsModel;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    OutgoingSelector *_outgoingSelector;
    NSArray *_availablePolicies;
}

@property(readonly) NSArray *availablePolicies; // @synthesize availablePolicies=_availablePolicies;
@property(readonly) OutgoingSelector *outgoingSelector; // @synthesize outgoingSelector=_outgoingSelector;
@property(readonly) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property(readonly) SettingsModel *settingsModel; // @synthesize settingsModel=_settingsModel;
- (void)dealloc;
- (void)resumeTimer;
- (void)pauseTimer;
- (void)closeAllConnectionWithOutDispatch;
- (void)closeAllConnection;
- (void)timeoutTimer;
- (void)transferConnectionToCONNECTConnection:(id)arg1 socket:(id)arg2 header:(id)arg3;
- (void)releaseTunnelConnection:(id)arg1;
- (void)releaseIncomingConnection:(id)arg1;
- (void)incomingConnection:(id)arg1;
- (void)socket:(id)arg1 didAcceptNewSocket:(id)arg2;
- (void)stopHTTPProxyServer;
- (BOOL)startHTTPProxyServerWithError:(id *)arg1;
- (void)addOutgoingConnectionToReuseQueue:(id)arg1;
- (id)reuseOutgoingConnectionToHost:(id)arg1;
- (id)initWithSettingsModel:(id)arg1;

@end

