//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Connector, NSData, NSError;

@protocol ConnectorDelegate <NSObject>
- (void)connector:(Connector *)arg1 didReadData:(NSData *)arg2 withTag:(long)arg3;
- (void)connectorDidDisconnect:(Connector *)arg1 withError:(NSError *)arg2;
- (void)connector:(Connector *)arg1 didWriteDataWithTag:(long)arg2;
- (void)connectorDidSetupFailed:(Connector *)arg1 error:(NSError *)arg2;
- (void)connectorDidBecomeAvailable:(Connector *)arg1;
@end

