//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"
#import "ConnectorDispatchQueueProvider-Protocol.h"
#import "SGSocketProtocol-Protocol.h"
#import "SGSocketProtocolDelegate-Protocol.h"
#import "ConnectorDelegate-Protocol.h"
#import "SGGCDAsyncSocket.h"
#import "ConnectionManager.h"
#import "SGLogConnectorSessionRecord.h"
#import "SGLogInterfaceSessionRecord.h"

@class NSString, SGLogConnectorSessionRecord, SGLogInterfaceSessionRecord;

@interface Connector : BaseObject <SGSocketProtocolDelegate>
{
    NSString *_targetHost;
    int _targetPort;
    id <SGSocketProtocol> _socket;
    __weak id <ConnectorDispatchQueueProvider> _manager;
    BOOL _initialized;
    double _lastReadDataTimeout;
    unsigned int _lastReadDataMaxSize;
    SGLogConnectorSessionRecord *_connectorSessionRecord;
    SGLogInterfaceSessionRecord *_interfaceSessionRecord;
    int _retry;
    __weak id <ConnectorDelegate> _delegate;
}
@property(nonatomic) __weak id <ConnectorDispatchQueueProvider> manager; // @synthesize manager=_manager;
@property(retain, nonatomic) id <SGSocketProtocol> socket; // @synthesize socket=_socket;
@property(nonatomic) int targetPort; // @synthesize targetPort=_targetPort;
@property(retain, nonatomic) NSString *targetHost; // @synthesize targetHost=_targetHost;
@property(nonatomic) __weak id <ConnectorDelegate> delegate; // @synthesize delegate=_delegate;

+ (id)connectorWithTargetHostname:(id)arg1 targetPort:(int)arg2 manager:(id)arg3;
- (id)remoteIPAddress;
- (id)localIPAddress;
- (void)createSocket;
- (void)disconnectWithError:(id)arg1;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)readDataWithTimeout:(double)arg1 maxLength:(unsigned int)arg2 tag:(long)arg3;
- (void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long)arg3;
- (void)socket:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)start;

@end