//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSData, NSString;

@interface DNSPacket : BaseObject
{
    unsigned short _identifier;
    unsigned short _queryRecordType;
    NSData *_rawData;
    NSString *_queryDomain;
}

@property(readonly, nonatomic) unsigned short queryRecordType; // @synthesize queryRecordType=_queryRecordType;
@property(readonly, nonatomic) NSString *queryDomain; // @synthesize queryDomain=_queryDomain;
@property(readonly, nonatomic) NSData *rawData; // @synthesize rawData=_rawData;
@property(readonly, nonatomic) unsigned short identifier; // @synthesize identifier=_identifier;
- (id)initWithPacketData:(id)arg1;

@end

