//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSError;

@interface GCDAsyncUdpSendPacket : NSObject
{
    NSData *buffer;
    double timeout;
    long tag;
    BOOL resolveInProgress;
    BOOL filterInProgress;
    NSArray *resolvedAddresses;
    NSError *resolveError;
    NSData *address;
    int addressFamily;
}

- (void).cxx_destruct;
- (id)initWithData:(id)arg1 timeout:(double)arg2 tag:(long)arg3;

@end

