//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSData, NSString;

@interface HTTPRequestHeader : NSObject
{
    BOOL _connectionKeepAlive;
    unsigned int _encoding;
    NSData *_rawRequestData;
    NSData *_parsedRequestData;
    NSString *_HTTPMethod;
    NSString *_URL;
    NSString *_host;
    NSString *_path;
    long long _requestContentLength;
}


@property(readonly) BOOL connectionKeepAlive; // @synthesize connectionKeepAlive=_connectionKeepAlive;
@property(readonly) long long requestContentLength; // @synthesize requestContentLength=_requestContentLength;
@property(readonly) NSString *path; // @synthesize path=_path;
@property(readonly) NSString *host; // @synthesize host=_host;
@property(readonly) NSString *URL; // @synthesize URL=_URL;
@property(readonly) NSString *HTTPMethod; // @synthesize HTTPMethod=_HTTPMethod;
@property(readonly) NSData *parsedRequestData; // @synthesize parsedRequestData=_parsedRequestData;
@property(readonly) NSData *rawRequestData; // @synthesize rawRequestData=_rawRequestData;
@property(readonly) unsigned int encoding; // @synthesize encoding=_encoding;
- (id)initWithData:(id)arg1;
+ (void)load;

@end

