//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSData, NSString;

@interface HTTPResponseHeader : NSObject
{
    BOOL _chunkedTransferEncoding;
    NSData *_rawResponseData;
    unsigned int _headerLength;
    int _statusCode;
    NSString *_connection;
    NSString *_httpVerison;
    long long _responseContentLength;
}

@property(readonly) NSString *httpVerison; // @synthesize httpVerison=_httpVerison;
@property(readonly) NSString *connection; // @synthesize connection=_connection;
@property(readonly) BOOL chunkedTransferEncoding; // @synthesize chunkedTransferEncoding=_chunkedTransferEncoding;
@property(readonly) int statusCode; // @synthesize statusCode=_statusCode;
@property(readonly) long long responseContentLength; // @synthesize responseContentLength=_responseContentLength;
@property(readonly) unsigned int headerLength; // @synthesize headerLength=_headerLength;
@property(readonly) NSData *rawResponseData; // @synthesize rawResponseData=_rawResponseData;
- (id)initWithData:(id)arg1;

@end

