//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "NSString-SGUtils.h"

@class NSData, NSString;

@interface HTTPRequestCONNECTHeader : NSObject
{
    NSData *_rawRequestData;
    NSString *_host;
}

@property(readonly) NSString *host; // @synthesize host=_host;
@property(readonly) NSData *rawRequestData; // @synthesize rawRequestData=_rawRequestData;
- (id)initWithGroupedData:(NSArray *)arg1 rawData:(NSData *)arg2;

@end

