//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <Foundation/Foundation.h>
#import "BaseObject.h"

#import "OutgoingConnectionDelegate-Protocol.h"
#import "SGSocketProtocolDelegate-Protocol.h"

@class ConnectionManager, HTTPRequestHeader, NSData, NSFileHandle, NSMutableData, NSString, OutgoingConnection, SGLogConversationRecord;

@interface IncomingConnection : BaseObject <OutgoingConnectionDelegate, SGSocketProtocolDelegate>
{
    BOOL _reading;
    OutgoingConnection *_outgoingConnection;
    ConnectionManager *_manager;
    SGLogConversationRecord *_record;
    NSMutableData *_requestHeaderData;
    NSData *_remaingData;
    NSFileHandle *_requestFileHandle;
    id <SGSocketProtocol> _socket;
    HTTPRequestHeader *_currentRequestHeader;
    int _status;
    double _lastActivityTimestamp;
}

@property(readonly) double lastActivityTimestamp; // @synthesize lastActivityTimestamp=_lastActivityTimestamp;
@property(readonly) int status; // @synthesize status=_status;
@property(readonly) HTTPRequestHeader *currentRequestHeader; // @synthesize currentRequestHeader=_currentRequestHeader;
@property(readonly) id <SGSocketProtocol> socket; // @synthesize socket=_socket;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (void)disconnectWithReason:(id)arg1;
- (void)setStatus:(int)arg1;
- (void)outgoingConnectionResponseDidComplete:(id)arg1 keepAlive:(BOOL)arg2;
- (void)outgoingConnection:(id)arg1 didReadResponseHeader:(id)arg2;
- (void)outgoingConnectionSocketDidDisconnect:(id)arg1 error:(id)arg2;
- (void)socket:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)outgoingConnection:(id)arg1 didReadData:(id)arg2;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)readFromSocket;
- (void)readHeader;
- (void)outgoingConnectionDidWriteBodyData:(id)arg1 length:(unsigned int)arg2;
- (void)outgoingConnectionDidWriteHeaderData:(id)arg1 length:(unsigned int)arg2;
- (void)outgoingConnectionSetupFailed:(id)arg1 error:(id)arg2;
- (void)writeServiceUnavailableResponseWithReason:(id)arg1;
- (void)outgoingConnectionDidBecomeAvailable:(id)arg1;
- (void)outgoingConnectionDidCompleteDNSLookup:(id)arg1;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (id)initWithSocket:(id)arg1 manager:(id)arg2;

@end

