//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <Foundation/Foundation.h>
#import "BaseObject.h"

@class NSData;

@interface IPv4Packet : BaseObject
{
    NSData *_rawData;
    unsigned char _protocol;
    unsigned int _sourceIP;
    unsigned int _destinationIP;
    unsigned int _headerLength;
    unsigned int _payloadLength;
}

@property(readonly, nonatomic) unsigned int payloadLength; // @synthesize payloadLength=_payloadLength;
@property(readonly, nonatomic) unsigned int headerLength; // @synthesize headerLength=_headerLength;
@property(readonly, nonatomic) unsigned int destinationIP; // @synthesize destinationIP=_destinationIP;
@property(readonly, nonatomic) unsigned int sourceIP; // @synthesize sourceIP=_sourceIP;
@property(readonly, nonatomic) unsigned char protocol; // @synthesize protocol=_protocol;
- (id)payloadData;
- (id)initWithPacketData:(id)arg1;

@end

