//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSLock, NSMutableDictionary, _LRUCacheNode;

@interface LRUCache : BaseObject
{
    _LRUCacheNode *_head;
    _LRUCacheNode *_tail;
    NSMutableDictionary *_map;
    NSLock *_lock;
    int _maxSize;
}

@property int maxSize; // @synthesize maxSize=_maxSize;
- (void).cxx_destruct;
- (id)allKeysInOrder;
- (id)allObjectsInOrder;
- (void)dealloc;
@property(readonly) int count;
- (id)dictionary;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)removeAllObject;
- (void)removeObjectForKey:(id)arg1 withLock:(BOOL)arg2;
- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)moveToHead:(id)arg1;
- (void)unlinkNodeForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithMaxSize:(int)arg1;
- (id)init;

@end

