//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (KDUtilities)
- (id)KD_shuffledArray;
- (id)KD_randomObject;
- (id)KD_arrayUsingMapEnumerateBlock:(CDUnknownBlockType)arg1;
@end

