//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (SGUtils)
- (id)componentsSeparatedByData:(id)arg1;
- (id)stringValue;
@end

