//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (SettingsModel)
- (id)trimmedComponentsSeparatedByString:(id)arg1 expectedLength:(unsigned int)arg2;
@end

