//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (SGUtils)
+ (id)byteStringWithLongLongValue:(long long)arg1;
+ (id)stringWithIPAddressUsingHostByteOrder:(unsigned int)arg1;
+ (id)stringWithIPAddressUsingNetworkByteOrder:(unsigned int)arg1;
- (id)trimmedString;
- (void)getHostname:(id *)arg1 andPort:(unsigned short *)arg2 withDefaultPortValue:(unsigned short)arg3;
- (unsigned int)IPAddressUsingHostByteOrder;
- (unsigned int)IPAddressUsingNetworkByteOrder;
- (BOOL)isIPCIDRString;
- (BOOL)isValidIPAddress;
- (BOOL)isIPv6Address;
- (BOOL)isIPAddress;
@end

