//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HTTPResponseHeader, NSData, NSError, OutgoingConnection;

@protocol OutgoingConnectionDelegate <NSObject>
- (void)outgoingConnectionResponseDidComplete:(OutgoingConnection *)arg1 keepAlive:(BOOL)arg2;
- (void)outgoingConnectionSocketDidDisconnect:(OutgoingConnection *)arg1 error:(NSError *)arg2;
- (void)outgoingConnectionDidWriteBodyData:(OutgoingConnection *)arg1 length:(unsigned int)arg2;
- (void)outgoingConnectionDidWriteHeaderData:(OutgoingConnection *)arg1 length:(unsigned int)arg2;
- (void)outgoingConnection:(OutgoingConnection *)arg1 didReadResponseHeader:(HTTPResponseHeader *)arg2;
- (void)outgoingConnection:(OutgoingConnection *)arg1 didReadData:(NSData *)arg2;
- (void)outgoingConnectionSetupFailed:(OutgoingConnection *)arg1 error:(NSError *)arg2;
- (void)outgoingConnectionDidBecomeAvailable:(OutgoingConnection *)arg1;
- (void)outgoingConnectionDidCompleteDNSLookup:(OutgoingConnection *)arg1;
@end

