//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "ConnectorDelegate.h"

@class ChunkedCodingParser, ConnectionManager, Connector, HTTPRequestHeader, HTTPResponseHeader, NSMutableData, NSString, SGLogConversationRecord;

@interface OutgoingConnection : BaseObject <ConnectorDelegate>
{
    Connector *_connector;
    HTTPResponseHeader *_responseHeader;
    ConnectionManager *_manager;
    NSMutableData *_responseHeaderData;
    unsigned long long _responseReceviedDataLength;
    BOOL _reading;
    unsigned int _writingHeaderLength;
    ChunkedCodingParser *_chunkedCodingParser;
    int _endType;
    NSString *_host;
    NSString *_hostname;
    unsigned short _port;
    double _lastActivityTimestamp;
    SGLogConversationRecord *_record;
    id <OutgoingConnectionDelegate> _delegate;
    HTTPRequestHeader *_processingHeader;
    int _status;
}

@property(readonly) unsigned short port; // @synthesize port=_port;
@property(readonly) NSString *hostname; // @synthesize hostname=_hostname;
@property(readonly) double lastActivityTimestamp; // @synthesize lastActivityTimestamp=_lastActivityTimestamp;
@property(readonly) NSString *host; // @synthesize host=_host;
@property(nonatomic) int status; // @synthesize status=_status;
@property(readonly) HTTPRequestHeader *processingHeader; // @synthesize processingHeader=_processingHeader;
@property(nonatomic) __weak id <OutgoingConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (id)remoteIPAddress;
- (id)localIPAddress;
- (void)dealloc;
- (void)disconnectWithReason:(id)arg1;
- (void)writeBodyData:(id)arg1;
- (void)connector:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)startNewRequestWithHeader:(id)arg1 record:(id)arg2;
- (void)reportDisconnectWithError:(id)arg1;
- (void)connectorDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)finishConversation;
- (void)continueReadData;
- (int)responseEndType;
- (void)connector:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)connectorDidSetupFailed:(id)arg1 error:(id)arg2;
- (void)connectorDidBecomeAvailable:(id)arg1;
- (void)startConnect;
- (id)initWithHost:(id)arg1 manager:(id)arg2;


@end

