//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject-SGLogger.h"

#import "GCDAsyncUdpSocketDelegate-Protocol.h"

@class NSArray, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface SGDNSClientBase : NSObject <GCDAsyncUdpSocketDelegate>
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSArray *_upstreamDNSServers;
    NSDictionary *_localDNSMap;
}

@property(retain) NSDictionary *localDNSMap; // @synthesize localDNSMap=_localDNSMap;
@property(retain) NSArray *upstreamDNSServers; // @synthesize upstreamDNSServers=_upstreamDNSServers;
- (void)udpSocketDidClose:(id)arg1 withError:(id)arg2;
- (void)udpSocket:(id)arg1 didNotSendDataWithTag:(long)arg2 dueToError:(id)arg3;
- (void)udpSocket:(id)arg1 didSendDataWithTag:(long)arg2;
- (void)udpSocket:(id)arg1 didNotConnect:(id)arg2;
- (void)closeSocketsForContext:(id)arg1;
- (void)createUpstreamSocketsForContext:(id)arg1;
- (id)init;

@end

