//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SGDNSClientBase.h"

#import "GCDAsyncUdpSocketDelegate.h"

@class LRUCache, NSMutableDictionary, NSObject<OS_dispatch_source>, NSString;

@interface SGDNSClient : SGDNSClientBase <GCDAsyncUdpSocketDelegate>
{
    NSObject<OS_dispatch_source> *_timer;
    unsigned short _queryIDCounter;
    NSMutableDictionary *_sentQueriesMap;
    NSMutableDictionary *_sentQueriesDomainMap;
    LRUCache *_cache;
}

+ (id)sharedInstance;
- (id)cachedResult;
- (void)timer;
- (void)flushCache;
- (void)udpSocket:(id)arg1 didReceiveData:(id)arg2 fromAddress:(id)arg3 withFilterContext:(id)arg4;
- (void)lookupUsingSystemLibrary:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)lookupDomain:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

