//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SGDNSClientBaseContext : NSObject
{
    NSArray *_sockets;
    double _startTime;
}

@property(retain, nonatomic) NSArray *sockets; // @synthesize sockets=_sockets;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;

@end

