//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SGDNSClientResult.h"

@class NSMutableDictionary, NSString;

@interface SGDNSClientMultipleResult : NSObject <SGDNSClientResult>
{
    NSMutableDictionary *_results;
    NSString *_domain;
}

- (void)reportAddressConnectFailed:(unsigned int)arg1;
- (unsigned int)recommandedResult;
- (id)allResult;
- (BOOL)isNotEmpty;
- (id)initWithResults:(id)arg1 domain:(id)arg2;

@end

