//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SGDNSClientBaseContext.h"

@class NSMutableArray, NSString, SGDNSPacket;

@interface SGDNSClientContext : SGDNSClientBaseContext
{
    unsigned short _identifier;
    NSString *_queryDomain;
    NSMutableArray *_completionHandlers;
    int _retry;
    SGDNSPacket *_queryPacket;
    double _lastRetryTime;
}

@property(retain, nonatomic) SGDNSPacket *queryPacket; // @synthesize queryPacket=_queryPacket;
@property(nonatomic) int retry; // @synthesize retry=_retry;
@property(nonatomic) double lastRetryTime; // @synthesize lastRetryTime=_lastRetryTime;
@property(retain, nonatomic) NSMutableArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(nonatomic) unsigned short identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *queryDomain; // @synthesize queryDomain=_queryDomain;

@end

