//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSString;

@interface SGDNSPacket : NSObject
{
    unsigned short _identifier;
    unsigned short _queryRecordType;
    NSData *_rawData;
    NSString *_queryDomain;
    NSArray *_answers;
}

+ (id)answerPacketWithData:(id)arg1;
+ (id)queryPacketWithDomain:(id)arg1 identifier:(unsigned short)arg2;
@property(readonly, nonatomic) NSArray *answers; // @synthesize answers=_answers;
@property(readonly, nonatomic) unsigned short queryRecordType; // @synthesize queryRecordType=_queryRecordType;
@property(readonly, nonatomic) NSString *queryDomain; // @synthesize queryDomain=_queryDomain;
@property(readonly, nonatomic) NSData *rawData; // @synthesize rawData=_rawData;
@property(readonly, nonatomic) unsigned short identifier; // @synthesize identifier=_identifier;

@end

