//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SGDNSClientResult.h"

@class NSString;

@interface SGDNSClientSingleResult : NSObject <SGDNSClientResult>
{
    unsigned int _result;
}
@property(readonly, copy) NSString *description;
- (BOOL)isNotEmpty;
- (void)reportAddressConnectFailed:(unsigned int)arg1;
- (unsigned int)recommandedResult;
- (id)allResult;
- (id)initWithResult:(unsigned int)arg1;

@end

