//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SGLogRecord.h"

@class NSFileHandle, NSMutableArray, NSString;

@interface SGLogConversationRecord : SGLogRecord
{
    NSMutableArray *_statusHistory;
    long _lastStatusStartTime;
    NSString *_logBasePath;
    NSFileHandle *_requestFileHandle;
    NSFileHandle *_responseFileHandle;
    BOOL _saved;
    BOOL _completed;
    BOOL _failed;
    NSString *_hostname;
    NSString *_remoteIPAddress;
    NSString *_localIPAddress;
    NSString *_URL;
    NSString *_method;
    NSString *_requestHeader;
    NSString *_responseHeader;
    NSString *_status;
}

@property(nonatomic) BOOL failed; // @synthesize failed=_failed;
@property(nonatomic) BOOL completed; // @synthesize completed=_completed;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *responseHeader; // @synthesize responseHeader=_responseHeader;
@property(retain, nonatomic) NSString *requestHeader; // @synthesize requestHeader=_requestHeader;
@property(retain, nonatomic) NSString *method; // @synthesize method=_method;
@property(retain, nonatomic) NSString *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSString *localIPAddress; // @synthesize localIPAddress=_localIPAddress;
@property(retain, nonatomic) NSString *remoteIPAddress; // @synthesize remoteIPAddress=_remoteIPAddress;
@property(readonly) NSString *hostname; // @synthesize hostname=_hostname;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)dealloc;
- (void)saveBodyData;
- (void)saveSummary;
- (id)responseBodyDataFileHandle;
- (id)requestBodyDataFileHandle;
- (id)statusHistory;
- (id)initWithHostname:(id)arg1 sessionDirectory:(id)arg2;

@end

