//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSDate;

@interface SGLogRecord : BaseObject
{
    unsigned int _inBytes;
    unsigned int _outBytes;
    NSDate *_startDate;
    unsigned int _inMaxSpeed;
    unsigned int _inCurrentSpeed;
    unsigned int _outMaxSpeed;
    unsigned int _outCurrentSpeed;
    unsigned int _inPreviousBytes;
    unsigned int _outPreviousBytes;
}

@property(nonatomic) unsigned int outPreviousBytes; // @synthesize outPreviousBytes=_outPreviousBytes;
@property(nonatomic) unsigned int inPreviousBytes; // @synthesize inPreviousBytes=_inPreviousBytes;
@property(nonatomic) unsigned int outCurrentSpeed; // @synthesize outCurrentSpeed=_outCurrentSpeed;
@property(nonatomic) unsigned int outMaxSpeed; // @synthesize outMaxSpeed=_outMaxSpeed;
@property(nonatomic) unsigned int inCurrentSpeed; // @synthesize inCurrentSpeed=_inCurrentSpeed;
@property(nonatomic) unsigned int inMaxSpeed; // @synthesize inMaxSpeed=_inMaxSpeed;
@property(nonatomic) unsigned int outBytes; // @synthesize outBytes=_outBytes;
@property(nonatomic) unsigned int inBytes; // @synthesize inBytes=_inBytes;
@property(readonly, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
- (void).cxx_destruct;
- (void)addOutBytes:(unsigned int)arg1;
- (void)addInBytes:(unsigned int)arg1;
- (id)init;

@end

