//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData, NSError, NSString;

@protocol SGSocketProtocolDelegate

@optional
- (void)socket:(id <SGSocketProtocol>)arg1 didWriteDataWithTag:(long)arg2;
- (void)socket:(id <SGSocketProtocol>)arg1 didReadData:(NSData *)arg2 withTag:(long)arg3;
- (void)socketDidDisconnect:(id <SGSocketProtocol>)arg1 withError:(NSError *)arg2;
- (void)socket:(id <SGSocketProtocol>)arg1 didConnectToHost:(NSString *)arg2 port:(unsigned short)arg3;
@end

