//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "SGSocketProtocolDelegate-Protocol.h"

@protocol SGSocketProtocol <NSObject>
@property(readonly) NSString *localHost;
@property(readonly) unsigned short connectedPort;
@property(readonly) NSString *connectedHost;
@property(readonly) BOOL isConnected;
@property(readonly) BOOL isDisconnected;
@property(retain) NSDictionary *TLSParameters;
@property __weak id <SGSocketProtocolDelegate> delegate;
- (void)writeData:(NSData *)arg1 withTimeout:(double)arg2 tag:(long)arg3;
- (void)readDataWithTimeout:(double)arg1 maxSize:(unsigned int)arg2 tag:(long)arg3;
- (void)disconnectAfterWritingHoldRef;
- (void)disconnect;
- (BOOL)connectToHost:(NSString *)arg1 onPort:(unsigned short)arg2 withTimeout:(double)arg3 error:(id *)arg4;
- (id)initWithDelegate:(id)arg1 delegateQueue:(NSObject<OS_dispatch_queue> *)arg2;
@end

