//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "ConnectorDelegate.h"
#import "SGSocketProtocolDelegate.h"

@class ConnectionManager, Connector, HTTPRequestHeader, NSMutableArray, NSString, SGLogConversationRecord;

@interface SGTunnelConnection : BaseObject <ConnectorDelegate, SGSocketProtocolDelegate>
{
    ConnectionManager *_manager;
    SGLogConversationRecord *_record;
    BOOL _inReading;
    BOOL _outReading;
    NSMutableArray *_dataWaitingSent;
    Connector *_connector;
    long long _receivedResponseDataLength;
    HTTPRequestHeader *_requestHeader;
    NSString *_host;
    NSString *_hostname;
    unsigned short _port;
    id <SGSocketProtocol> _socket;
    double _lastActivityTimestamp;
}

@property(readonly) double lastActivityTimestamp; // @synthesize lastActivityTimestamp=_lastActivityTimestamp;
@property(readonly) id <SGSocketProtocol> socket; // @synthesize socket=_socket;
@property(readonly) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)connector:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)connectorDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)continueReadConnectorData;
- (void)connector:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)writeServiceUnavailableResponseWithReason:(id)arg1;
- (void)connectorDidSetupFailed:(id)arg1 error:(id)arg2;
- (void)connectorDidBecomeAvailable:(id)arg1;
- (void)socket:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)disconnectWithReason:(id)arg1;
- (void)readFromSocket;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)connectToHost;
- (id)initWithSocket:(id)arg1 CONNECTHeader:(id)arg2 manager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

