//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SGDNSClientBaseContext.h"

@class DNSPacket;

@interface STIPLayerDNSForwarderContext : SGDNSClientBaseContext
{
    unsigned short _clientPort;
    unsigned short _outgoingQueryIdentifier;
    DNSPacket *_dnsPacket;
    unsigned int _clientAddress;
}

@property(nonatomic) unsigned short outgoingQueryIdentifier; // @synthesize outgoingQueryIdentifier=_outgoingQueryIdentifier;
@property(nonatomic) unsigned short clientPort; // @synthesize clientPort=_clientPort;
@property(nonatomic) unsigned int clientAddress; // @synthesize clientAddress=_clientAddress;
@property(retain, nonatomic) DNSPacket *dnsPacket; // @synthesize dnsPacket=_dnsPacket;
- (void).cxx_destruct;

@end

