//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSString;

@interface STNetworkInterfaceManager : BaseObject
{
    NSString *_primaryIPAddress;
    NSString *_WiFiIPAddress;
    NSString *_WWANIPAddress;
    NSString *_bluetoothIPAddress;
}

+ (id)sharedInstance;
@property(readonly) NSString *bluetoothIPAddress; // @synthesize bluetoothIPAddress=_bluetoothIPAddress;
@property(readonly) NSString *WWANIPAddress; // @synthesize WWANIPAddress=_WWANIPAddress;
@property(readonly) NSString *WiFiIPAddress; // @synthesize WiFiIPAddress=_WiFiIPAddress;
@property(readonly) NSString *primaryIPAddress; // @synthesize primaryIPAddress=_primaryIPAddress;
- (void).cxx_destruct;
- (int)interfaceMTUWithName:(id)arg1;
- (void)updateInterfaceInfo;
- (id)init;

@end

