//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSData;

@interface STProxyConnectionWritePacket : BaseObject
{
    NSData *_data;
    long _tag;
}

@property(nonatomic) long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;

@end

