//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "SGSocketProtocol.h"

@class NSDictionary, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, STProxyConnectionWritePacket;

@interface STProxyConnection : BaseObject <SGSocketProtocol>
{
    struct tcp_pcb *_tcp;
    NSMutableArray *_pendingData;
    NSMutableArray *_writingDataQueue;
    BOOL _reading;
    long _readingTag;
    STProxyConnectionWritePacket *_writingPacket;
    unsigned int _writingDataOffset;
    BOOL _disconnectAfterWriting;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSObject<OS_dispatch_queue> *_socketQueue;
    NSString *_connectedHost;
    unsigned short _connectedPort;
    id <SGSocketProtocolDelegate> _delegate;
}

+ (void)load;
@property __weak id <SGSocketProtocolDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly) unsigned short connectedPort; // @synthesize connectedPort=_connectedPort;
@property(readonly) NSString *connectedHost; // @synthesize connectedHost=_connectedHost;
- (BOOL)connectToHost:(id)arg1 onPort:(unsigned short)arg2 withTimeout:(double)arg3 error:(id *)arg4;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2;
@property(retain) NSDictionary *TLSParameters;
@property(readonly) NSString *localHost;
@property(readonly) BOOL isConnected;
@property(readonly) BOOL isDisconnected;
- (void)disconnectAfterWritingHoldRef;
- (void)disconnect;
- (void)processWritingQueue;
- (void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long)arg3;
- (void)processReadData;
- (void)readDataWithTimeout:(double)arg1 maxSize:(unsigned int)arg2 tag:(long)arg3;
- (void)TCPDidSentDataWithLength:(unsigned short)arg1;
- (void)processUnsentData;
- (BOOL)sendDataToClient:(const void *)arg1 len:(unsigned short)arg2;
- (void)abandon;
- (void)closeWithReason:(id)arg1;
- (void)TCPError:(BOOL)arg1;
- (void)TCPDidReceiveData:(id)arg1;
- (void)TCPClientClose;
- (void)dealloc;
- (id)initWithTCP:(struct tcp_pcb *)arg1 connectedHost:(id)arg2 connectedPort:(unsigned short)arg3 delegateQueue:(id)arg4 socketQueue:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

