//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "ConnectorDelegate.h"

@class Connector, NSData, NSMutableArray, NSString, SGLogConversationRecord, STTCPConnectionManager;

@interface STTCPConnection : BaseObject <ConnectorDelegate>
{
    struct tcp_pcb *_tcp;
    STTCPConnectionManager *_manager;
    double _lastActivityTimestamp;
    Connector *_connector;
    BOOL _connectorReading;
    BOOL _pendingConnection;
    NSMutableArray *_pendingData;
    NSData *_waitingData;
    SGLogConversationRecord *_record;
    unsigned int _writingDataOffset;
    BOOL _disconnectAfterWriting;
    unsigned short _port;
    NSString *_realHostname;
}

@property(readonly) double lastActivityTimestamp; // @synthesize lastActivityTimestamp=_lastActivityTimestamp;
@property(readonly, nonatomic) unsigned short port; // @synthesize port=_port;
@property(readonly, nonatomic) NSString *realHostname; // @synthesize realHostname=_realHostname;
- (void).cxx_destruct;
- (void)disconnectAfterWritingHoldRef;
- (void)connector:(id)arg1 didWriteDataWithTag:(long)arg2;
- (void)writeData:(id)arg1;
- (void)connectorDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)connectorContinueReadData;
- (void)TCPDidSentDataWithLength:(unsigned short)arg1;
- (void)processUnsentData;
- (BOOL)sendDataToClient:(const void *)arg1 len:(unsigned short)arg2;
- (void)connector:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
- (void)connectorDidSetupFailed:(id)arg1 error:(id)arg2;
- (void)connectorDidBecomeAvailable:(id)arg1;
- (void)closeWithReason:(id)arg1;
- (void)TCPError:(BOOL)arg1;
- (void)TCPDidReceiveData:(id)arg1;
- (void)TCPClientClose;
- (void)dealloc;
- (id)initWithTCP:(struct tcp_pcb *)arg1 realHostname:(id)arg2 port:(unsigned short)arg3 manager:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

