//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

#import "SGSocketProtocol.h"

@class NSDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString, NWTCPConnection;

@interface STTCPSocket : BaseObject <SGSocketProtocol>
{
    NWTCPConnection *_connection;
    BOOL _disconnetedEventRaised;
    NSObject<OS_dispatch_source> *_timeoutTimer;
    BOOL _connected;
    id <SGDNSClientResult> _dnsResult;
    unsigned int _usingDNSResult;
    unsigned short _connectedPort;
    id <SGSocketProtocolDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSDictionary *_TLSParameters;
    NSString *_connectedHost;
}

@property(readonly) unsigned short connectedPort; // @synthesize connectedPort=_connectedPort;
@property(readonly) NSString *connectedHost; // @synthesize connectedHost=_connectedHost;
@property(retain) NSDictionary *TLSParameters; // @synthesize TLSParameters=_TLSParameters;
@property(retain) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property __weak id <SGSocketProtocolDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)raiseDisconnectEvent:(id)arg1;
@property(readonly) NSString *localHost;
@property(readonly) BOOL isDisconnected;
@property(readonly) BOOL isConnected;
- (void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long)arg3;
- (void)readDataWithTimeout:(double)arg1 maxSize:(unsigned int)arg2 tag:(long)arg3;
- (void)disconnectAfterWritingHoldRef;
- (void)disconnectAfterWriting;
- (void)disconnect;
- (void)connectionStateDidChange;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)connectTimeout;
- (void)setupTCPSessionWithHostname:(id)arg1;
- (BOOL)connectToHost:(id)arg1 onPort:(unsigned short)arg2 withTimeout:(double)arg3 error:(id *)arg4;
- (BOOL)connectToHost:(id)arg1 onPort:(unsigned short)arg2 viaInterface:(id)arg3 withTimeout:(double)arg4 error:(id *)arg5;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

