//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseObject.h"

@class NSData;

@interface UDPPacket : BaseObject
{
    NSData *_rawData;
    unsigned short _sourcePort;
    unsigned short _destinationPort;
}

@property(readonly, nonatomic) unsigned short destinationPort; // @synthesize destinationPort=_destinationPort;
@property(readonly, nonatomic) unsigned short sourcePort; // @synthesize sourcePort=_sourcePort;
- (void).cxx_destruct;
- (id)payloadData;
- (id)initWithPacketData:(id)arg1;

@end

